services:
  - type: web
    name: portfolio-quality-tracker
    env: node
    region: frankfurt
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: NODE_ENV=production node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    disk:
      name: portfolio-data
      mountPath: /data
      sizeGB: 1
